// <auto-generated />
namespace ProjektPazigFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ZmianamodeluExpense : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZmianamodeluExpense));
        
        string IMigrationMetadata.Id
        {
            get { return "202005071445253_Zmiana modelu Expense"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
