// <auto-generated />
namespace ProjektPazigFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DodaniemodeuDebet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodaniemodeuDebet));
        
        string IMigrationMetadata.Id
        {
            get { return "202005211726444_Dodanie modeu Debet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
